In [1]:
#Functions

In [3]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True


In [6]:
# Print out type of var1
print(type(var1))

<class 'list'>


In [7]:
# Print out length of var1
print(len(var1))

4


In [8]:
# Convert var2 to an integer: out2
out2=int(var2)

In [9]:
print(out2)

1


In [11]:
?pow

In [12]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [13]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

In [14]:
# Paste together first and second: full
full=first+second

In [15]:
print(full)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [16]:
# Sort full in descending order: full_sorted
full_sorted=sorted(full,reverse=True)

In [17]:
# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [ ]:
#Methods

In [ ]:
#String Methods
#Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover 
#them in more detail, you can always type help(str) in the IPython Shell.

#A string place has already been created for you to experiment with.

In [18]:
# string to experiment with: place
place = "poolhouse"

In [19]:
# Use upper() on place: place_up
place_up= place.upper()


In [20]:
# Print out place and place_up
print(place);print(place_up)

poolhouse
POOLHOUSE


In [21]:
# Print out the number of o's in place
print(place.count("o"))

3


In [ ]:
#List Methods
#Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

#index(), to get the index of the first element of a list that matches its input and
#count(), to get the number of times an element appears in a list.
#You'll be working on the list with the area of different parts of a house: areas.

In [22]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

In [23]:
# Print out the index of the element 20.0
print(areas.index(20.0))

2


In [24]:
# Print out how often 9.50 appears in areas
print(areas.count(9.50))

1


In [ ]:
#List Methods (2)
#Most list methods will change the list they're called on. Examples are:

#append(), that adds an element to the list it is called on,
#remove(), that removes the first element of a list that matches the input, and
#reverse(), that reverses the order of the elements in the list it is called on.
#You'll be working on the list with the area of different parts of the house: areas.

In [25]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

In [26]:
# Use append twice to add poolhouse and garage size
areas.append(24.5);areas.append(15.45)

In [27]:
# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [28]:
# Reverse the orders of the elements in areas
areas.reverse()

In [29]:
# Print out areas
print(areas)

[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [31]:
#Import Packages

In [ ]:
import numpy

In [32]:
numpy.array([1,2,3])

array([1, 2, 3])

In [33]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
#use only 1 specific function from numpy
from numpy import array

In [ ]:
#Import package
#As a data scientist, some notions of geometry never hurt. Let's refresh some of the basics.

#For a fancy clustering algorithm, you want to find the circumference, , and area, , of a circle. When the radius of the circle is r, you can calculate  and  as:


#To use the constant pi, you'll need the math package. A variable r is already coded in the script. Fill in the code to calculate C and A and see how the print() functions create some nice printouts.

In [34]:
# Definition of radius
r = 0.43

In [35]:
# Import the math package
import math

In [36]:
# Calculate C
C = 2*math.pi*r

In [37]:
# Calculate A
A = math.pi*r*r


In [38]:
# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [ ]:
#Selective import
#General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

In [ ]:
#Perform a selective import from the math package where you only import the radians function.
#Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to dist. You can calculate this as r * phi, where r is the radius and phi is the angle in radians. To convert an angle in degrees to an angle in radians, use the radians() function, which you just imported.
#Print out dist.

In [39]:
# Definition of radius
r = 192500

In [40]:
# Import radians function of math package
from math import radians

In [41]:
# Travel distance of Moon over 12 degrees. Store in dist.
dist=r*radians(12)

In [42]:
print(dist)

40317.10572106901


In [ ]:
#Numpy


In [ ]:
#Your First NumPy Array
#In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of numpy, a powerful package to do data science.

#A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [ ]:
#Import the numpy package as np, so that you can refer to numpy with np.
#Use np.array() to create a numpy array from baseball. Name this array np_baseball.
#Print out the type of np_baseball to check that you got it right.

In [43]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [8]:
# Import the numpy package as np
import numpy as np

In [45]:
# Create a numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

In [46]:
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [47]:
# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [ ]:
#Baseball players' height
#You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?

#height_in is already available and the numpy package is loaded, so you can start straight away (Source: stat.ucla.edu).

In [ ]:
#importing CSV file

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("baseball.csv")
df

Name Team        Position  Height  Weight    Age PosCategory
0       Adam_Donachie  BAL         Catcher      74     180  22.99     Catcher
1           Paul_Bako  BAL         Catcher      74     215  34.69     Catcher
2     Ramon_Hernandez  BAL         Catcher      72     210  30.78     Catcher
3        Kevin_Millar  BAL   First_Baseman      72     210  35.43   Infielder
4         Chris_Gomez  BAL   First_Baseman      73     188  35.71   Infielder
...               ...  ...             ...     ...     ...    ...         ...
1010    Brad_Thompson  STL  Relief_Pitcher      73     190  25.08     Pitcher
1011    Tyler_Johnson  STL  Relief_Pitcher      74     180  25.73     Pitcher
1012   Chris_Narveson  STL  Relief_Pitcher      75     205  25.19     Pitcher
1013    Randy_Keisler  STL  Relief_Pitcher      75     190  31.01     Pitcher
1014      Josh_Kinney  STL  Relief_Pitcher      73     195  27.92     Pitcher

[1015 rows x 7 columns]

In [5]:
#convert column to the list
hight_in=df['Height'].to_list()

In [6]:
print(hight_in)

[74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73,

In [9]:
#create a Numpy Array from the list
np_hight_in=np.array(hight_in)
print(np_hight_in)

[74 74 72 ... 75 75 73]


In [11]:
# Convert np_height_in to m: np_height_m by multiplaying it with 0.0254
np_height_m=np_hight_in*0.0254
print(np_height_m)

[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [ ]:
#Baseball Player's BMI

In [ ]:
#The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: height_in and weight_lb. height_in is in inches and weight_lb is in pounds.

#It's now possible to calculate the BMI of each baseball player. Python code to convert height_in to a numpy array with the correct units is already available in the workspace. Follow the instructions step by step and finish the game!

In [16]:
#Create a numpy array from the weight_lb list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.

#have to create a list for Weight_lb *** PM COMMENT***

weight_lb=df['Weight'].to_list()

#creating a numpy array in KG units by multiplying by 0.453592

np_weight_kg=np.array(weight_lb)*0.453592

print(np_weight_kg)

[81.64656 97.52228 95.25432 ... 92.98636 86.18248 88.45044]


In [17]:
#Use np_height_m and np_weight_kg to calculate the BMI of each player. Use the following equation: BMI=weight(kg)/height(m)2 Save the numpy as BMI

BMI=np_weight_kg/np_height_m**2

print(BMI)



[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


In [ ]:
#Lightweight baseball players

In [ ]:
#To subset both regular Python lists and numpy arrays, you can use square brackets:

#x = [4 , 9 , 6, 3, 1]
#x[1]
#import numpy as np
#y = np.array(x)
#y[1]
#For numpy specifically, you can also use boolean numpy arrays:

#high = y > 5
#y[high]
#The code that calculates the BMI of all baseball players is already included. Follow the instructions and reveal interesting things from the data!

In [20]:
#Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 21. You can use the < operator for this. Name the array light.

#create the light array
light=BMI<21

print(light)
print(type(light))

[False False False ... False False False]
<class 'numpy.ndarray'>


In [21]:
#Print out a numpy array with the BMIs of all baseball players whose BMI is below 21. Use light inside square brackets to do a selection on the bmi array.

print(BMI[light])


[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


In [23]:
x = ["a", "b", "c"]
print(x[1])

np_x = np.array(x)
print(np_x[1])


b
b


In [ ]:
#Your First 2D NumPy Array
#Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.

#In this exercise, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

In [24]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball=np.array(baseball)
# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [25]:
print(baseball)

[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]


In [26]:
print(df)

                 Name Team        Position  Height  Weight    Age PosCategory
0       Adam_Donachie  BAL         Catcher      74     180  22.99     Catcher
1           Paul_Bako  BAL         Catcher      74     215  34.69     Catcher
2     Ramon_Hernandez  BAL         Catcher      72     210  30.78     Catcher
3        Kevin_Millar  BAL   First_Baseman      72     210  35.43   Infielder
4         Chris_Gomez  BAL   First_Baseman      73     188  35.71   Infielder
...               ...  ...             ...     ...     ...    ...         ...
1010    Brad_Thompson  STL  Relief_Pitcher      73     190  25.08     Pitcher
1011    Tyler_Johnson  STL  Relief_Pitcher      74     180  25.73     Pitcher
1012   Chris_Narveson  STL  Relief_Pitcher      75     205  25.19     Pitcher
1013    Randy_Keisler  STL  Relief_Pitcher      75     190  31.01     Pitcher
1014      Josh_Kinney  STL  Relief_Pitcher      73     195  27.92     Pitcher

[1015 rows x 7 columns]


In [28]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [29]:
np_mat + np.array([10, 10])


array([[11, 12],
       [13, 14],
       [15, 16]])

In [30]:
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [31]:
import re

In [32]:
! pip install re

ERROR: Could not find a version that satisfies the requirement re (from versions: none)
ERROR: No matching distribution found for re
