In [1]:
#Functions

In [3]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True


In [6]:
# Print out type of var1
print(type(var1))

<class 'list'>


In [7]:
# Print out length of var1
print(len(var1))

4


In [8]:
# Convert var2 to an integer: out2
out2=int(var2)

In [9]:
print(out2)

1


In [11]:
?pow

In [12]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [13]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

In [14]:
# Paste together first and second: full
full=first+second

In [15]:
print(full)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [16]:
# Sort full in descending order: full_sorted
full_sorted=sorted(full,reverse=True)

In [17]:
# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [ ]:
#Methods

In [ ]:
#String Methods
#Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover 
#them in more detail, you can always type help(str) in the IPython Shell.

#A string place has already been created for you to experiment with.

In [18]:
# string to experiment with: place
place = "poolhouse"

In [19]:
# Use upper() on place: place_up
place_up= place.upper()


In [20]:
# Print out place and place_up
print(place);print(place_up)

poolhouse
POOLHOUSE


In [21]:
# Print out the number of o's in place
print(place.count("o"))

3


In [ ]:
#List Methods
#Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

#index(), to get the index of the first element of a list that matches its input and
#count(), to get the number of times an element appears in a list.
#You'll be working on the list with the area of different parts of a house: areas.

In [22]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

In [23]:
# Print out the index of the element 20.0
print(areas.index(20.0))

2


In [24]:
# Print out how often 9.50 appears in areas
print(areas.count(9.50))

1


In [ ]:
#List Methods (2)
#Most list methods will change the list they're called on. Examples are:

#append(), that adds an element to the list it is called on,
#remove(), that removes the first element of a list that matches the input, and
#reverse(), that reverses the order of the elements in the list it is called on.
#You'll be working on the list with the area of different parts of the house: areas.

In [25]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

In [26]:
# Use append twice to add poolhouse and garage size
areas.append(24.5);areas.append(15.45)

In [27]:
# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [28]:
# Reverse the orders of the elements in areas
areas.reverse()

In [29]:
# Print out areas
print(areas)

[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [31]:
#Import Packages

In [ ]:
import numpy

In [32]:
numpy.array([1,2,3])

array([1, 2, 3])

In [33]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
#use only 1 specific function from numpy
from numpy import array

In [ ]:
#Import package
#As a data scientist, some notions of geometry never hurt. Let's refresh some of the basics.

#For a fancy clustering algorithm, you want to find the circumference, , and area, , of a circle. When the radius of the circle is r, you can calculate  and  as:


#To use the constant pi, you'll need the math package. A variable r is already coded in the script. Fill in the code to calculate C and A and see how the print() functions create some nice printouts.

In [34]:
# Definition of radius
r = 0.43

In [35]:
# Import the math package
import math

In [36]:
# Calculate C
C = 2*math.pi*r

In [37]:
# Calculate A
A = math.pi*r*r


In [38]:
# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [ ]:
#Selective import
#General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

In [ ]:
#Perform a selective import from the math package where you only import the radians function.
#Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to dist. You can calculate this as r * phi, where r is the radius and phi is the angle in radians. To convert an angle in degrees to an angle in radians, use the radians() function, which you just imported.
#Print out dist.

In [39]:
# Definition of radius
r = 192500

In [40]:
# Import radians function of math package
from math import radians

In [41]:
# Travel distance of Moon over 12 degrees. Store in dist.
dist=r*radians(12)

In [42]:
print(dist)

40317.10572106901


In [ ]:
#Numpy


In [ ]:
#Your First NumPy Array
#In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of numpy, a powerful package to do data science.

#A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [ ]:
#Import the numpy package as np, so that you can refer to numpy with np.
#Use np.array() to create a numpy array from baseball. Name this array np_baseball.
#Print out the type of np_baseball to check that you got it right.

In [43]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [44]:
# Import the numpy package as np
import numpy as np

In [45]:
# Create a numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

In [46]:
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [47]:
# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [ ]:
#Baseball players' height
#You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?

#height_in is already available and the numpy package is loaded, so you can start straight away (Source: stat.ucla.edu).